const express = require('express');
const router = express.Router();
const apps = require('../controller/appFunctions');
const auth = require('../middleware/authentication');
router.get('/',auth.checkStatus, apps.homepage);
router.get('/auth', apps.showAuthenPage);
router.get('/addQuestion', auth.checkToken,apps.createQuestion);
router.get('/logOut', apps.loggingOut);
router.post('/signUp', apps.signUp);
router.post('/logIn', apps.logIn);
module.exports = router;